name: kafka
# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  #push:
  #  branches: [ "main" ]
  #pull_request:
  #  branches: [ "main" ]
  # Allows you to run this workflow manually from the Actions tab
  repository_dispatch:
    types: [kafka]
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  kafka:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write

    steps:
    - uses: actions/checkout@v4
    
    - name: Start Kafka
      uses: 280780363/kafka-action@v1.0
      with:
        kafka version: "latest" # Optional, kafka version
        zookeeper version: "latest" # Optional, zookeeper version
        kafka port: 9092 # Optional, kafka port
        zookeeper port: 2181 # Optional, zookeeper port
        auto create topic: "true" # Optional, auto create kafka topic
    - run: pip install -r requirements.txt
    
